// src/types/ErrorTypes.ts

export enum ErrorType {
  NAT_TRAVERSAL_FAILED = 'NAT_TRAVERSAL_FAILED',
  TIMEOUT = 'TIMEOUT',
  DATA_CHANNEL_FAILED = 'DATA_CHANNEL_FAILED',
  PEER_OFFLINE = 'PEER_OFFLINE',
  WEBSOCKET_FAILED = 'WEBSOCKET_FAILED',
  MISSING_DATA = 'MISSING_DATA',
  UNKNOWN = 'UNKNOWN',
}
